components:
  paths:
    Details:
      get:
        summary: Details
        description: Query the API configuration details.
        operationId: ConfigurationDetails
        tags:
          - Configuration
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    images:
                      type: object
                      properties:
                        base_url:
                          type: string
                          example: 'http://image.tmdb.org/t/p/'
                        secure_base_url:
                          type: string
                          example: 'https://image.tmdb.org/t/p/'
                        backdrop_sizes:
                          type: array
                          items:
                            type: string
                            example: w300
                        logo_sizes:
                          type: array
                          items:
                            type: string
                            example: w45
                        poster_sizes:
                          type: array
                          items:
                            type: string
                            example: w92
                        profile_sizes:
                          type: array
                          items:
                            type: string
                            example: w45
                        still_sizes:
                          type: array
                          items:
                            type: string
                            example: w92
                      required:
                        - base_url
                        - secure_base_url
                        - backdrop_sizes
                        - logo_sizes
                        - poster_sizes
                        - profile_sizes
                        - still_sizes
                    change_keys:
                      type: array
                      items:
                        type: string
                        example: adult
                  required:
                    - images
                    - change_keys
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
    Countries:
      get:
        summary: Countries
        description: Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
        operationId: ConfigurationCountries
        tags:
          - Configuration
        parameters:
          - $ref: 'commons.yml#/components/parameters/Language'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Country'
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
    Jobs:
      get:
        summary: Jobs
        description: Get the list of the jobs and departments we use on TMDB.
        operationId: ConfigurationJobs
        tags:
          - Configuration
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Department'
                  example:
                    - department: 'Actors'
                      jobs: ['Actor', 'Cameo', 'Special Guest', 'Voice']
                    - department: 'Directing'
                      jobs: ['Director', 'Other']
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
    Languages:
      get:
        summary: Languages
        description: Get the list of languages (ISO 639-1 tags) used throughout TMDB.
        operationId: ConfigurationLanguages
        tags:
          - Configuration
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Language'
                  example:
                    - iso_639_1: 'en'
                      english_name: 'English'
                      name: 'English'
                    - iso_639_1: 'eo'
                      english_name: 'Esperanto'
                      name: 'Esperanto'
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
    PrimaryTranslations:
      get:
        summary: Primary Translations
        description: Get a list of the officially supported translations on TMDB.
        operationId: ConfigurationPrimaryTranslations
        tags:
          - Configuration
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
                  example: ['en-GB', 'en-US', 'eo-EO']
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
    Timezones:
      get:
        summary: Timezones
        description: Get the list of timezones used throughout TMDB.
        operationId: ConfigurationTimezones
        tags:
          - Configuration
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    additionalProperties: false
                    properties:
                      iso_3166_1:
                        type: string
                        description: ISO 3166-1 tag
                        minLength: 2
                        maxLength: 2
                        pattern: '^[A-Z]{2}$'
                      zones:
                        type: array
                        items:
                          type: string
                    required:
                      - iso_3166_1
                      - zones
                  example:
                    - iso_3166_1: ES
                      zones: [Europe/Madrid, Africa/Ceuta, Atlantic/Canary]
                    - iso_3166_1: GB
                      zones: [Europe/London]
          '401':
            $ref: 'commons.yml#/components/responses/Unauthorized'
  schemas:
    Country:
      type: object
      additionalProperties: false
      properties:
        iso_3166_1:
          type: string
          description: ISO 3166-1 tag
          minLength: 2
          maxLength: 2
          pattern: '^[A-Z]{2}$'
          example: AD
        english_name:
          type: string
          example: Andorra
        native_name:
          type: string
          example: Andorra
      required:
        - iso_3166_1
        - english_name
    Department:
      type: object
      additionalProperties: false
      properties:
        department:
          type: string
          description: The name of the department
        jobs:
          type: array
          items:
            type: string
      required:
        - department
        - jobs
    Language:
      type: object
      additionalProperties: false
      properties:
        iso_639_1:
          type: string
          description: ISO 3166-1 tag
          minLength: 2
          maxLength: 2
          pattern: '^[a-z]{2}$'
        english_name:
          type: string
        name:
          type: string
      required:
        - iso_639_1
        - english_name