openapi: 3.0.3
info:
  title: TMDB API
  description: The Movie Database (TMDB) API
  version: 0.1.0
servers:
  - url: 'https://api.themoviedb.org/3'
tags:
  - name: Configuration
paths:
  /configuration:
    $ref: 'configuration.yml#/components/paths/Details'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []