openapi: 3.0.3
info:
  title: TMDB API
  description: The Movie Database (TMDB) API
  version: 0.2.2
servers:
  - url: 'https://api.themoviedb.org/3'
tags:
  - name: Configuration
paths:
  /configuration:
    $ref: 'configuration.yml#/components/paths/Details'
  /configuration/countries:
    $ref: 'configuration.yml#/components/paths/Countries'
components:
  parameters:
    Language:
      $ref: 'commons.yml#/components/parameters/Language'
  responses:
    Unauthorized:
      $ref: 'commons.yml#/components/responses/Unauthorized'
  schemas:
    Country:
      $ref: 'configuration.yml#/components/schemas/Country'
    Error:
      $ref: "commons.yml#/components/schemas/Error"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []