---
extends: default

ignore:
  - openapi.yml
  - dist/
  - parts/

rules:
  document-start:
    ignore: dist/openapi.yaml
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    ignore: dist/openapi.yaml
    max: 120
    # allow-non-breakable-words: true
    # allow-non-breakable-inline-mappings: true
  quoted-strings:
    quote-type: double
    required: false
  truthy:
    ignore: .github/workflows/*.yaml
