# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default

ignore: openapi.yml

rules:
  document-start:
    present: false
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    # allow-non-breakable-words: true
    # allow-non-breakable-inline-mappings: true
  truthy:
    ignore: .github/workflows/*.yml
