---
extends: default

ignore: /openapi.yml

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    ignore:
      - ./dist/openapi.yaml
    max: 120
    # allow-non-breakable-words: true
    # allow-non-breakable-inline-mappings: true
  truthy:
    ignore: .github/workflows/*.yml
