---
get:
  summary: Countries
  description: Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
  operationId: ConfigurationCountries
  tags:
    - Configuration
  parameters:
    - $ref: '../components/parameters/query/LanguageParam.yaml'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/Country.yaml'
            example:
              - iso_3166_1: 'GB'
                english_name: 'United Kingdom'
                native_name: 'United Kingdom'
              - iso_3166_1: 'US'
                english_name: 'United States of America'
                native_name: 'United States'
    '401':
      $ref: '../components/responses/401Unauthorized.yaml'
    '429':
      $ref: '../components/responses/429TooManyRequests.yaml'
