---
get:
  summary: Timezones
  description: Get the list of timezones used throughout TMDB.
  operationId: ConfigurationTimezones
  tags:
    - Configuration
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/CountryWithTimezones.yaml'
            example:
              - iso_3166_1: ES
                zones: [Europe/Madrid, Africa/Ceuta, Atlantic/Canary]
              - iso_3166_1: GB
                zones: [Europe/London]
    '401':
      $ref: '../components/responses/401Unauthorized.yaml'
    '429':
      $ref: '../components/responses/429TooManyRequests.yaml'
